let resume=null;
const result=document.getElementById('resumeResult');
document.getElementById('logout').onclick=()=>{localStorage.removeItem('token');location='/login.html'};
document.getElementById('upload').onclick=async()=>{const f=document.getElementById('file').files[0];if(!f)return uploadMsg.textContent='Choose a PDF or DOCX file first.';const fd=new FormData();fd.append('file',f);const r=await fetch('/api/resumes/upload',{method:'POST',headers:{Authorization:'Bearer '+localStorage.token},body:fd});const d=await r.json();if(!r.ok){uploadMsg.className='error';uploadMsg.textContent=d.detail||'Upload failed';return}resume=d;uploadMsg.className='success';uploadMsg.textContent='Resume analyzed successfully.';renderResume();loadJobs();};
function renderResume(){result.classList.remove('hidden');result.innerHTML=`<h2>Resume Analysis</h2><p><b>Name:</b> ${esc(resume.full_name)} &nbsp; <b>Email:</b> ${esc(resume.email)} &nbsp; <b>Phone:</b> ${esc(resume.phone)}</p><p><b>Summary:</b> ${esc(resume.summary)}</p><h3>Technical Skills</h3>${resume.technical_skills.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}<h3>Soft Skills</h3>${resume.soft_skills.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}<h3>Education</h3><ul>${resume.education.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Experience</h3><ul>${resume.experience.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}
async function loadJobs(){const q=encodeURIComponent(document.getElementById('search').value||'');const jobs=await api('/api/jobs?q='+q);jobsList.innerHTML=jobs.map(j=>`<div class="job"><h3>${esc(j.title)}</h3><p>${esc(j.company)} · ${esc(j.location)} · ${esc(j.experience_level)}</p><p>${esc(j.description)}</p><div>${j.required_skills.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div><button class="btn" onclick="matchJob(${j.id})">Match Resume</button></div>`).join('')||'<p>No jobs found.</p>'}
window.matchJob=async id=>{if(!resume)return alert('Upload a resume first.');const m=await api(`/api/matching/resume/${resume.id}/job/${id}`,{method:'POST'});const imp=await api(`/api/matching/resume/${resume.id}/improvement?job_id=${id}`);answer.innerHTML=`<div class="card"><div class="score">${m.score}% match</div><p>${esc(m.explanation)}</p><b>Matching:</b> ${m.matching_skills.map(esc).join(', ')||'None'}<br><b>Missing:</b> ${m.missing_skills.map(esc).join(', ')||'None'}<hr><b>Improvement guidance:</b><p>${esc(imp.guidance)}</p></div>`;location.hash='career'};
document.getElementById('searchBtn').onclick=loadJobs;loadJobs();
document.getElementById('ask').onclick=async()=>{if(!question.value.trim())return;const d=await api('/api/career/ask',{method:'POST',body:JSON.stringify({question:question.value,resume_id:resume?.id||null})});answer.innerHTML=`<div class="job"><p>${esc(d.answer)}</p><small>Sources: ${(d.sources||[]).map(s=>esc(s.source)).join(', ')||'None'}</small></div>`};
